### ISSUE TITLE
Add Image Dimentions

### ISSUE THREAD

**Issue by aliebuck** [ceee/grunt-datauri#3]
Would be great if there was an option to add the `width` and `height` attributes to an image. And maybe `background-size` for svg or retina (`@2x`) images.

For example:

``` css
.test-png {
    background-image: url("data:image/png;base64,iVBORw0KGgoAAAAN.....");
    width: 24px;
    height: 24px;
}
.test-svg {
    background-image: url("data:image/svg+xml;base64,R0lGODlhZABkAJEA.....");
    background-size: 80px 50px;
    width: 80px;
    height: 50px;
}
```
